version: '3.7'
services:
    database:
        image: 'mysql:latest'
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            - '3306'
    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]
volumes:
  db_data: {}